import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy | Warpindex",
  description: "Privacy Policy for Warpindex - Learn how we handle and protect your personal information.",
};

export default function PrivacyPage() {
  return (
    <main className="flex flex-1 flex-col">
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex flex-col items-center justify-center text-center mb-12">
          <Link href="/" className="text-3xl text-primary hover:text-primary/90 transition-colors mb-4">
            Warpindex
          </Link>
          <h1 className="text-4xl font-medium">Privacy Policy</h1>
          <p className="mt-4 text-xl text-muted-foreground">Learn how we handle and protect your personal information</p>
        </div>

        {/* Content */}
        <div className="prose prose-gray max-w-4xl mx-auto dark:prose-invert">
          <h4><strong>Introduction</strong></h4>
          <p>
            This Privacy Policy explains how Warpindex, Inc. (&quot;Warpindex&quot;, or &quot;we&quot;, &quot;us&quot; or &quot;our&quot;) handles personal information that we collect
          </p>
          <ul>
            <li>through our service and website at www.warpindex.com and https://app.warpindex.com (the &quot;Service&quot;);</li>
            <li>in connection with our marketing activities;</li>
            <li>at events we host; and</li>
            <li>in other settings where we post this Privacy Policy.</li>
          </ul>

          <p>
            Warpindex respects your privacy rights and is committed to transparency in how we collect, use, share and safeguard your personal information.
            If you have any questions or concerns about your personal information or this Privacy Policy, email us at contact@warpindex.com.
          </p>

          <p>
            We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy.
            Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.
          </p>

          <p>
            Our Terms and Conditions (&quot;Terms&quot;) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (&quot;agreement&quot;).
          </p>

          <h4><strong>Definitions</strong></h4>
          <p><strong>SERVICE</strong> means the https://www.warpindex.com website operated by Warpindex, Inc.</p>

          <p><strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>

          <p><strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>

          <p><strong>COOKIES</strong> are small files stored on your device (computer or mobile device).</p>

          <p><strong>DATA CONTROLLER</strong> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>

          <p><strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</p>

          <p><strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.</p>

          <p><strong>THE USER</strong> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>

          <h4><strong>Information Collection and Use</strong></h4>
          <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

          <h4><strong>Types of Data Collected</strong></h4>

          <h5><strong>Personal Data</strong></h5>
          <p>
            While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&quot;Personal Data&quot;).
            Personally identifiable information may include, but is not limited to:
          </p>
          <ol>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Phone number</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
          </ol>

          <p>
            We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you.
            You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.
          </p>

          <h5><strong>Usage Data</strong></h5>
          <p>
            We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device (&quot;Usage Data&quot;).
          </p>

          <p>
            This Usage Data may include information such as your computer&apos;s Internet Protocol address (e.g. IP address), browser type, browser version,
            the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>

          <p>
            When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID,
            the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
          </p>

          <h5><strong>Tracking Cookies Data</strong></h5>
          <p>
            We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.
          </p>

          <p>
            Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device.
            Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
          </p>

          <p>
            You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
          </p>

          <p>Examples of Cookies we use:</p>
          <ol>
            <li><strong>Session Cookies:</strong> We use Session Cookies to operate our Service.</li>
            <li><strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various settings.</li>
            <li><strong>Security Cookies:</strong> We use Security Cookies for security purposes.</li>
            <li><strong>Advertising Cookies:</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
          </ol>

          <h5><strong>Other Data</strong></h5>
          <p>
            While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship,
            registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification,
            professional training, employment agreements, non-disclosure agreements, information on bonuses and compensation, information on marital status,
            family members, social security (or other taxpayer identification) number, office location and other data.
          </p>

          <h4><strong>Contact Us</strong></h4>
          <p>If you have any questions about this Privacy Policy, please contact us:</p>

          <p>By email: contact@warpindex.com</p>
        </div>
      </div>
    </main>
  );
}
